swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /customer:
    get:
      operationId: "customer.get_customer"
      tags:
        - "Customer"
      summary: "The customer data structure supported by the server application"
      description: "Read the list of customers"
      responses:
        200:
          description: "Successful read customer list operation"
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"
  /customer/{lname}:
    get:
      operationId: customer.get_customer_by_lastname
      tags:
        - Customer
      summary: Read one customer from the customer list
      description: Read one customer from the customer list by last name
      parameters:
        - name: lname
          in: path
          description: Last name of the person to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read customer from customer list operation
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              timestamp:
                type: string